feature/gdev-60
ghga-de/sandbox-notification pull request #10
Opened 2021-07-21 13:59 UTC by ac-jorellanaf

https://jira.verbis.dkfz.de/browse/GDEV-60
Implemented message brokerage with RabbitMQ using a producer-subscriber setup using topic exchanges and message acknowledgments.

2021-07-21 13:59 UTC, ac-jorellanaf commented
Word of warning: I did not implement the repo template to this yet.

2021-07-21 14:45 UTC, MoritzHahn1337 commented on sandbox_notification/config/notif_schema.json
> +    "required": ["sender", "recipient", "recipient_name", "recipient_email", "message", "SMTP_server", "SMTP_username", "SMTP_password"]
Is json case-sensitive?
In any case, I think we should use either lowercase, or uppercase for SMTP, but not mix them.

2021-07-22 08:39 UTC, ac-jorellanaf commented on sandbox_notification/config/notif_schema.json
> +    "required": ["sender", "recipient", "recipient_name", "recipient_email", "message", "SMTP_server", "SMTP_username", "SMTP_password"]
There was an issue with using lowercase names because those were in the namespace for the mail library. I also didn't use the schema in the python code, so this is unused for now, pending further evaluation.

2021-07-23 14:20 UTC, alamgirmani commented on .devcontainer/dev_launcher
> +    python sender.py "$RNAME" "$REMAIL" "$SMTPSERV" "$SMTPPORT" "$SMTPUSER" "$SMTPPASS"
The calling method provides recipient name, recipient mail_address and the message. We configure the SMTP parameters in a config file or read from db.

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/receiver.py
> +def send_email(recipient_email, message, smtp_server, smtp_port, smtp_username, smtp_password):
server, port, username and password will come from db or config

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/receiver.py
> +connection = pika.BlockingConnection(
Blocking or non blocking?

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/receiver.py
> +channel.queue_bind(exchange='notifications', queue='notifications', routing_key='#.notifications.#')
wrap up these lines in a method.

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/receiver.py
> +            print('  [>] Email notification sent.\n')
We can log these messages.

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/sender.py
> +  main(args)
create a run_cli method?

2021-07-23 14:20 UTC, alamgirmani commented on sandbox_notification/sender.py
> +  connection.close()
rabbit_mq related codes can be wrapped up in a method

2021-07-23 14:20 UTC, alamgirmani commented on test/app_test.py
> +    config_data = config.get_config(CONFIG_YAML)
test send mail.

2021-07-23 14:39 UTC, KerstenBreuer requested changes
Very cool.

We should integrate the config parsing from the ghga_service_chassis_lib at some point to get following parameters:
- smtp server
- smtp port
- smtp user
- smtp password
- max_attempts
- sender_email
- email_subject

But let's leave that to another PR, this is already getting quite big ;)

@ac-jorellanaf, should I create a task in Jira for that?

2021-07-23 14:39 UTC, KerstenBreuer commented on sandbox_notification/channels.py
> +def callback(ch, method, properties, body):
@ac-jorellanaf, could you add type hints for this function header?

2021-07-23 14:39 UTC, KerstenBreuer commented on test/app_test.py
> +    config_data = config.get_config(CONFIG_YAML)
That's a good idea, could we maybe mock an smtp server?

2021-07-27 15:09 UTC, ac-jorellanaf commented on test/app_test.py
> +    config_data = config.get_config(CONFIG_YAML)
I would need help in setting up unit testing in python for this, unless you mean just a new script?

2021-07-27 15:16 UTC, ac-jorellanaf commented on sandbox_notification/channels.py
> +def callback(ch, method, properties, body):
Will do in the next commit.

2021-07-27 15:16 UTC, ac-jorellanaf commented on sandbox_notification/receiver.py
> +def send_email(recipient_email, message, smtp_server, smtp_port, smtp_username, smtp_password):
I think this should be done for GDEV-123 instead, since that would already be half the work for it. 😁

2021-07-27 15:18 UTC, ac-jorellanaf commented on sandbox_notification/receiver.py
> +connection = pika.BlockingConnection(
For now, blocking. Making the connection to RabbitMQ async would need to be a task of its own.

2021-07-28 11:57 UTC, ac-jorellanaf commented on .devcontainer/dev_launcher
> +    python sender.py "$RNAME" "$REMAIL" "$SMTPSERV" "$SMTPPORT" "$SMTPUSER" "$SMTPPASS"
I think this should be done for the other task, which is for making it compatible with other services?

2021-07-28 17:14 UTC, ac-jorellanaf commented on sandbox_notification/channels.py
> +def callback(ch, method, properties, body):
29240b05f73a0cba0d81f9b62dbac1d20c19cb8d

2021-07-29 15:16 UTC, KerstenBreuer approved these changes
Thx for the improvements.

2021-07-30 08:10 UTC, merged