feature/gdev-131
ghga-de/sandbox-notification pull request #12
Opened 2021-08-06 12:36 UTC by ac-jorellanaf

2021-08-06 13:10 UTC, ac-jorellanaf commented
Not sure why the check is failing. 🤷‍♂️

2021-08-09 09:22 UTC, MoritzHahn1337 commented
Fixed that for you

2021-08-09 15:05 UTC, KerstenBreuer requested changes
Thank you. Here are a couple of comments.

I have some suggestions regarding the configuration. If you like we can solve that in a separate PR?!

2021-08-09 15:05 UTC, KerstenBreuer commented on .devcontainer/docker-compose.yml
>        - ghga_mnet
Why do we need to define our own bridge network? Doesn't Docker Compose do that automatically? (also referring to line 36-37, and 44-46)

2021-08-09 15:05 UTC, KerstenBreuer commented on .devcontainer/dev_config.yaml
> +# TODO: Add app specific configuration
You are right @ac-jorellanaf, we should name this `.devcontainer/sandbox-notification.yaml` as you did below. Please remove this file. I have also created a new ticket to fix that in the template repo, too (GDEV-143).

2021-08-09 15:05 UTC, KerstenBreuer commented on .gitattributes
> +#
```suggestion
```

2021-08-09 15:05 UTC, KerstenBreuer commented on openapi.yaml
> +# This file was autogenerated, please do not modify.
We don't need this file, because the service has not web API.

2021-08-09 15:05 UTC, KerstenBreuer commented on .devcontainer/openapi_from_app.py
> +#!/usr/bin/env python3
We don't need this file, because the service has not web API.

2021-08-09 15:05 UTC, KerstenBreuer commented on sandbox_notification/__main__.py
>      subscribe(args.topic_str)
The topic string should be handed over via the Config class. See `sandbox_notification/config.py `.

So we don't need a CLI interface here and can directly run:
 ```
config = get_config() # from ../config
subscribe(config.topic_str)
```

2021-08-09 15:05 UTC, KerstenBreuer commented on .devcontainer/sandbox-notification.yaml
> +language: Greek
These config parameters are not needed, because the service won't have a web API.

2021-08-09 15:05 UTC, KerstenBreuer commented on example-config.yaml
> +auto_reload: False
These config parameters are not needed, because the service won't have a web API.

2021-08-09 15:05 UTC, KerstenBreuer commented on sandbox_notification/api.py
> +    return "Hello World."
We don't need this file, because the service has not web API.

2021-08-09 15:05 UTC, KerstenBreuer commented on sandbox_notification/channels.py
> +# Copyright 2021 Universität Tübingen, DKFZ and EMBL
This was originally meant to hold the content of the `topics.py` file.
For now let's remove this file. But let's try to find a good name for the python module that holds the async API (pub/sub). I created GDEV-144.

2021-08-09 15:05 UTC, KerstenBreuer commented on sandbox_notification/config.py
> +class Config(ApiConfigBase):
We don't need to inherit from `ApiConfigBase`, since this has no web API. We might need a similar Config Base class for async services, too. I created GDEV-145. But for the scope of the sandbox study, just put the params you need directly here in the Config class

2021-08-09 15:05 UTC, KerstenBreuer commented on sandbox_notification/core/send.py
>  MAX_ATTEMPTS = 5
This should go into the config class

2021-08-09 15:05 UTC, KerstenBreuer commented on setup.cfg
> +    ghga-service-chassis-lib[api]==0.1.0
```suggestion
    ghga-service-chassis-lib==0.1.0
```

2021-08-09 15:05 UTC, KerstenBreuer commented on tests/integration/test_api.py
> +# Copyright 2021 Universität Tübingen, DKFZ and EMBL
We don't need this file, because the service has not web API.

2021-08-10 13:19 UTC, KerstenBreuer commented on sandbox_notification/__main__.py
>      subscribe(args.topic_str)
Will be done in GDEV-123.

2021-08-10 13:20 UTC, KerstenBreuer commented on .devcontainer/sandbox-notification.yaml
> +language: Greek
Will be done in GDEV-123.

2021-08-10 13:20 UTC, KerstenBreuer commented on example-config.yaml
> +auto_reload: False
Will be done in GDEV-123.

2021-08-10 13:20 UTC, KerstenBreuer commented on sandbox_notification/core/send.py
>  MAX_ATTEMPTS = 5
Will be done in GDEV-123.

2021-08-11 08:59 UTC, ac-jorellanaf commented on .devcontainer/docker-compose.yml
>        - ghga_mnet
Yes, but there are some advantages, see https://docs.docker.com/network/bridge/

2021-08-11 09:17 UTC, ac-jorellanaf commented
@KerstenBreuer Not sure whether to restore `openapi_from_app.py` or delete that section in the SCA.

2021-08-11 10:13 UTC, KerstenBreuer commented
@ac-jorellanaf, no worries, you can delete the check since this service will not have a web API.

Let me know when I should re-review it

2021-08-13 08:09 UTC, KerstenBreuer commented on .devcontainer/docker-compose.yml
>        - ghga_mnet
I think this article only applies to standalone Docker not Docker Compose. As far as I understand, Docker compose is creating a "user-defined" bridge network automatically. I.e. you can also address other containers by name.

2021-08-13 08:46 UTC, ac-jorellanaf commented on .devcontainer/docker-compose.yml
>        - ghga_mnet
Would you prefer if I removed it?

2021-08-13 09:28 UTC, KerstenBreuer commented on .devcontainer/docker-compose.yml
>        - ghga_mnet
As long as we don't have a use for it, it should be removed, let's remove it, yes.

2021-08-13 11:35 UTC, KerstenBreuer approved these changes

2021-08-13 11:37 UTC, merged