feature/cd_flow
ghga-de/sandbox-notification pull request #9
Opened 2021-07-19 09:12 UTC by walzph

same as https://github.com/ghga-de/sandbox-storage/pull/15

2021-07-23 08:45 UTC, ac-jorellanaf requested changes
Can you merge the dev branch to this and resolve the conflicts? Thanks.

2021-08-04 08:20 UTC, KerstenBreuer commented
Hi @ac-jorellanaf, I rebased the branch to the current dev. Should be fine now. Can you check?

2021-08-04 09:06 UTC, ac-jorellanaf commented on Dockerfile
> +#     http://www.apache.org/licenses/LICENSE-2.0
Did you also change this?

2021-08-04 09:06 UTC, ac-jorellanaf approved these changes

2021-08-04 09:13 UTC, KerstenBreuer commented on Dockerfile
> +#     http://www.apache.org/licenses/LICENSE-2.0
Hm, yes I changed the Dockerfile. In the Template I have it says `http`, but `https` is working, too. Let's keep it like this to be consistent with the microservice_template_repository?!

2021-08-04 12:10 UTC, ac-jorellanaf commented on Dockerfile
> +#     http://www.apache.org/licenses/LICENSE-2.0
It should be https at this stage of the WWW, but it seems Apache keeps their license info to use http, so let's keep it as such.

2021-08-04 12:12 UTC, merged